{% set python_min = "3.10" %}
{% set name = "glasspy" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/glasspy-{{ version }}.tar.gz
  sha256: 777423bb6ec8cb6262426e3c6e0e9506aa53e2ccb74540f5e1c349bdd8e62b79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - joblib >=1.5.0
    - onnxruntime >=1.23
    - requests >=2.30.0
    - python >={{ python_min }}
    - pandas >=2.0.0
    - lmfit >=1.2.0
    - chemparse >=0.1.0
    - scikit-learn >=1.5.0
    - compress-pickle >=2.1.0
    - pytorch >=2.0.0
    - lightning >=2.1.0
    - platformdirs >=4.5.1

test:
  imports:
    - glasspy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/drcassar/glasspy
  summary: Python module for scientists working with glass materials
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
