{% set name = "glasspy" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/glasspy-{{ version }}.tar.gz
  sha256: 1c4f2e1dffebc90caa459236d37bc5d497f245ac5aeda5312d2b044e19aae8f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - pandas >=1.3
    - lmfit >=1.0.0
    - chemparse >=0.1.0
    - scikit-learn ==1.2.0
    - compress-pickle >=2.1.0
    - pytorch
    - lightning >=2.0.0
    - platformdirs

test:
  imports:
    - glasspy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/drcassar/glasspy
  summary: Python module for scientists working with glass materials
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
