{% set python_min = '3.10' %}
{% set name = "glasspy" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/glasspy-{{ version }}.tar.gz
  sha256: 0a73632f93aaf4e585777268d3fc4578ee77f3149a28a8ef67e987b161e7c02b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - requests
    - python >={{ python_min }}
    - pandas >=2.0.0
    - lmfit >=1.2.0
    - chemparse >=0.1.0
    - scikit-learn >=1.5.0
    - compress-pickle >=2.1.0
    - pytorch
    - lightning >=2.1.0
    - platformdirs

test:
  imports:
    - glasspy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/drcassar/glasspy
  summary: Python module for scientists working with glass materials
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
