{% set name = "glasspy" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/glasspy-{{ version }}.tar.gz
  sha256: d8adf1f8cd44fe1b1bcac7426b42af437e55c2cf53c51c29237d5399b248b6f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - requests
    - python >=3.10
    - pandas >=2.0.0
    - lmfit >=1.2.0
    - chemparse >=0.1.0
    - scikit-learn >=1.5.0
    - compress-pickle >=2.1.0
    - pytorch
    - lightning >=2.1.0
    - platformdirs

test:
  imports:
    - glasspy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/drcassar/glasspy
  summary: Python module for scientists working with glass materials
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
